"""init

Revision ID: 5b2859a21e4b
Revises: 
Create Date: 2022-01-17 12:57:07.322183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2859a21e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercide_set_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('reps_achieved', sa.Integer(), nullable=True),
    sa.Column('set', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_plan_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('exercise_set_instance_Id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_reps_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('rep_count', sa.Integer(), nullable=True),
    sa.Column('set_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('rest_between_plans', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=True),
    sa.Column('rest_min', sa.Integer(), nullable=True),
    sa.Column('rest_max', sa.Integer(), nullable=True),
    sa.Column('weight_increment', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('workout_schedule_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workout_schedule_id'], ['workout_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_reps_set_workout_plan',
    sa.Column('workout_plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_reps_set_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_reps_set_id'], ['exercise_reps_set.id'], ),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['workout_plan.id'], ),
    sa.PrimaryKeyConstraint('workout_plan_id', 'exercise_reps_set_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_reps_set_workout_plan')
    op.drop_table('workout_plan')
    op.drop_table('workout_schedule')
    op.drop_table('exercise_reps_set')
    op.drop_table('workout_instance')
    op.drop_table('workout')
    op.drop_table('exercise')
    op.drop_table('exercide_set_instance')
    # ### end Alembic commands ###
